name: Run MATLAB build
on: [push]
jobs:
  build:
    name: Build
    runs-on: self-hosted
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Run build
        uses: matlab-actions/run-build@v2
