name: Run MATLAB build

on:
  push:
  workflow_call:

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Check out dependencies
        uses: actions/checkout@v4
        with:
          repository: rks/file-exchange-toolbox
          path: tmp/repository/FileExchangeToolbox
          sparse-checkout: |
            resources
            toolbox
      - run: |
          tree -a -I .git $GITHUB_WORKSPACE
      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v2
        with:
          cache: true
          release: latest-including-prerelease
      - name: Run build
        uses: matlab-actions/run-build@v2
