name: Spike action

on:
  workflow_dispatch:

jobs:
  scratch:
    name: Scratch
    runs-on: ubuntu-latest
    steps:
      - name: Check out dependency
        uses: actions/checkout@v4
        with:
          repository: rks/file-exchange-toolbox
          path: ${RUNNER_TEMP}/local-repository/FileExchangeToolbox
          sparse-checkout: |
            resources
            toolbox
      - run: |
          pwd
          ls -lA ${GITHUB_WORKSPACE}
          ls -lA ${RUNNER_TEMP}
