name: Spike action

on:
  workflow_dispatch:

jobs:
  tag:
    name: Create tag
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Extract package version
        run: node --eval 'console.log(JSON.parse(fs.readFileSync("resources/mpackage.json")).version)'
